name: Deploy SiteCraft

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # AQUI ESTÁ A CORREÇÃO PRINCIPAL
      - name: Instalar Dependências do Site
        run: npm install --legacy-peer-deps

      - name: Criar Versão Final (Build)
        run: npm run build

      - name: Instalar Dependências das Funções
        run: cd functions && npm install --legacy-peer-deps

      - name: Publicar no Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions --force --project criador-de-site-1a91d
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
